-- =============================================================================
-- Eşsiz Tatlar Hatay'dan - Ürün Seed
-- category_id: 1=Zeytinyağı, 2=Baharat, 3=Sabun, 4=Peynir, 5=Kuru Gıda, 6=Tahin
-- =============================================================================

SET NAMES utf8mb4;

INSERT INTO `products` (`category_id`, `name`, `slug`, `short_description`, `description`, `sku`, `price`, `compare_at_price`, `currency`, `stock_quantity`, `low_stock_threshold`, `weight_grams`, `unit`, `image`, `is_active`, `is_featured`, `meta_title`, `meta_description`) VALUES
(1, 'Naturel Sızma Zeytinyağı 5 Lt', 'naturel-sizma-zeytinyagi-5-lt', 'Hatay Antakya soğuk sıkım naturel sızma zeytinyağı, 5 litre teneke.', 'Hatay\'ın bereketli topraklarında yetişen zeytinlerden soğuk sıkım yöntemiyle üretilen naturel sızma zeytinyağı. Hiçbir kimyasal işlem uygulanmadan, doğal ve sağlıklı.', 'ET-ZY-001', 1250.00, 1499.00, 'TRY', 50, 5, 5400, 'litre', 'assets/images/products/zeytinyagi-5lt.jpg', 1, 1, 'Naturel Sızma Zeytinyağı 5 Lt - Eşsiz Tatlar', 'Hatay soğuk sıkım naturel sızma zeytinyağı 5 litre. Doğal ve sağlıklı.'),
(1, 'Soğuk Sıkım Zeytinyağı 1 Lt Cam', 'soguk-sikim-zeytinyagi-1-lt-cam', 'Cam şişede 1 litre soğuk sıkım zeytinyağı.', 'İlk soğuk sıkım yöntemiyle elde edilen, aroması yüksek zeytinyağı. Cam şişede saklama kolaylığı.', 'ET-ZY-002', 350.00, NULL, 'TRY', 100, 10, 1100, 'litre', 'assets/images/products/zeytinyagi-1lt.jpg', 1, 1, 'Soğuk Sıkım Zeytinyağı 1 Lt - Eşsiz Tatlar', 'Cam şişede 1 litre soğuk sıkım zeytinyağı.'),
(2, 'Künefe Şekeri 1 Kg', 'kunefe-sekeri-1-kg', 'Gerçek künefe için özel ince öğütülmüş künefe şekeri.', 'Hatay\'ın meşhur künefesinin vazgeçilmez malzemesi. İnce öğütülmüş, taze ve doğal.', 'ET-BH-001', 85.00, NULL, 'TRY', 200, 20, 1000, 'kg', 'assets/images/products/kunefe-sekeri.jpg', 1, 1, 'Künefe Şekeri 1 Kg - Eşsiz Tatlar', 'Gerçek künefe için özel künefe şekeri 1 kg.'),
(2, 'Sumak 250 Gr', 'sumak-250-gr', 'Doğal kırmızı sumak, 250 gram paket.', 'Salata, kebap ve yemeklerinize eşsiz lezzet katan doğal sumak.', 'ET-BH-002', 45.00, 55.00, 'TRY', 150, 15, 250, 'gr', NULL, 1, 0, 'Sumak 250 Gr - Eşsiz Tatlar', 'Doğal sumak 250 gram.'),
(2, 'Pul Biber 200 Gr', 'pul-biber-200-gr', 'Hatay\'ın meşhur acı pul biberi, 200 gram.', 'Hatay\'a özgü, doğal acı pul biber. Kahvaltı ve yemeklerde kullanım.', 'ET-BH-003', 65.00, NULL, 'TRY', 120, 10, 200, 'gr', NULL, 1, 0, 'Pul Biber 200 Gr - Eşsiz Tatlar', 'Hatay pul biber 200 gram.'),
(3, 'Defne Sabunu 3\'lü Paket', 'defne-sabunu-3lu-paket', 'Doğal defne yaprağı sabunu, 3 adet paket.', 'Antakya\'nın geleneksel defne sabunu. Cilt dostu, doğal içerikli.', 'ET-SB-001', 75.00, NULL, 'TRY', 80, 10, 300, 'adet', 'assets/images/products/defne-sabunu.jpg', 1, 1, 'Defne Sabunu 3\'lü - Eşsiz Tatlar', 'Doğal defne sabunu 3\'lü paket.'),
(3, 'Zeytinyağı Sabunu 2\'li', 'zeytinyagi-sabunu-2li', 'Saf zeytinyağı ile üretilmiş doğal sabun, 2 adet.', 'Cildi yumuşatan, doğal zeytinyağı sabunu.', 'ET-SB-002', 55.00, NULL, 'TRY', 90, 10, 200, 'adet', NULL, 1, 0, 'Zeytinyağı Sabunu 2\'li - Eşsiz Tatlar', 'Doğal zeytinyağı sabunu 2\'li.'),
(4, 'Künefe Peyniri 400 Gr', 'kunefe-peyniri-400-gr', 'Taze künefe peyniri, 400 gram paket.', 'Künefe ve tatlılar için özel taze peynir. Hatay\'dan taze sipariş.', 'ET-PY-001', 120.00, NULL, 'TRY', 40, 5, 400, 'gr', NULL, 1, 1, 'Künefe Peyniri 400 Gr - Eşsiz Tatlar', 'Taze künefe peyniri 400 gram.'),
(5, 'Kuru İncir 500 Gr', 'kuru-incir-500-gr', 'Doğal kuru incir, 500 gram paket.', 'Hatay\'ın güneşinde kurutulmuş, doğal kuru incir. Atıştırmalık ve kahvaltı.', 'ET-KG-001', 95.00, 110.00, 'TRY', 60, 10, 500, 'gr', NULL, 1, 0, 'Kuru İncir 500 Gr - Eşsiz Tatlar', 'Doğal kuru incir 500 gram.'),
(6, 'Tahin 1 Kg', 'tahin-1-kg', 'Susamdan üretilmiş doğal tahin, 1 kg cam kavanoz.', 'Kahvaltı ve tatlılar için doğal tahin. Katkısız.', 'ET-TH-001', 180.00, NULL, 'TRY', 70, 10, 1100, 'kg', NULL, 1, 0, 'Tahin 1 Kg - Eşsiz Tatlar', 'Doğal tahin 1 kg.'),
(6, 'Üzüm Pekmezi 750 Ml', 'uzum-pekmezi-750-ml', 'Geleneksel usul üzüm pekmezi, 750 ml cam.', 'Doğal üzüm pekmezi. Kahvaltı ve hamur işlerinde kullanım.', 'ET-PK-001', 95.00, NULL, 'TRY', 55, 10, 950, 'ml', NULL, 1, 0, 'Üzüm Pekmezi 750 Ml - Eşsiz Tatlar', 'Doğal üzüm pekmezi 750 ml.');
