-- =============================================================================
-- Eşsiz Tatlar Hatay'dan - Statik Sayfalar Seed
-- =============================================================================

SET NAMES utf8mb4;

INSERT INTO `pages` (`slug`, `title`, `content`, `meta_title`, `meta_description`, `is_active`, `sort_order`) VALUES
('hakkimizda', 'Hakkımızda', '<p>Eşsiz Tatlar Hatay\'dan olarak, Hatay\'ın zengin mutfak kültürünü ve doğal ürünlerini Türkiye\'nin dört bir yanına ulaştırıyoruz.</p><p>Antakya\'nın kadim lezzetlerini, soğuk sıkım zeytinyağından künefe şekerine, defne sabunundan doğal baharatlara kadar en taze ve doğal haliyle sizlere sunuyoruz. Kalite ve güvenilirlik önceliğimizdir.</p>', 'Hakkımızda - Eşsiz Tatlar Hatay\'dan', 'Hatay doğal ürünleri ve hikayemiz hakkında bilgi edinin.', 1, 1),
('iletisim', 'İletişim', '<p><strong>Adres:</strong> Örnek Mah. Hatay Cad. No: 1, 31000 Antakya / Hatay</p><p><strong>Telefon:</strong> 0326 123 45 67</p><p><strong>E-posta:</strong> info@essiztatlar.com</p><p><strong>Çalışma saatleri:</strong> Pazartesi - Cumartesi 09:00 - 18:00</p>', 'İletişim - Eşsiz Tatlar Hatay\'dan', 'Bizimle iletişime geçin. Adres, telefon ve e-posta bilgileri.', 1, 2),
('sss', 'Sıkça Sorulan Sorular', '<h3>Siparişim ne zaman kargoya verilir?</h3><p>Ödeme onayı sonrası 1-2 iş günü içinde kargoya teslim edilir.</p><h3>Kargo ücreti ne kadar?</h3><p>150 TL ve üzeri siparişlerde kargo ücretsizdir. Altı siparişlerde kargo ücreti sepette hesaplanır.</p><h3>İade koşulları nelerdir?</h3><p>Ürün teslim tarihinden itibaren 14 gün içinde, hasarsız ve orijinal ambalajında iade edilebilir.</p>', 'Sıkça Sorulan Sorular - Eşsiz Tatlar', 'Sipariş, kargo ve iade hakkında SSS.', 1, 3),
('gizlilik', 'Gizlilik Politikası', '<p>Kişisel verileriniz 6698 sayılı KVKK kapsamında işlenmekte ve saklanmaktadır. Ödeme bilgileriniz güvenli ödeme altyapısı ile işlenir, şifrelerinizi saklamıyoruz.</p><p>İletişim bilgileriniz yalnızca sipariş ve müşteri hizmetleri süreçlerinde kullanılır; üçüncü taraflarla paylaşılmaz.</p>', 'Gizlilik Politikası - Eşsiz Tatlar', 'KVKK ve gizlilik politikamız.', 1, 4),
('mesafeli-satis', 'Mesafeli Satış Sözleşmesi', '<p>Bu siteden yapılan alışverişler 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği hükümlerine tabidir.</p><p>Cayma hakkı: Teslim tarihinden itibaren 14 gün içinde ürünü iade ederek cayma hakkınızı kullanabilirsiniz. Tüketici ödeme yükümlülüğü ve cayma hakkı kullanılamayan ürünler yönetmelikte belirtilmiştir.</p>', 'Mesafeli Satış Sözleşmesi - Eşsiz Tatlar', 'Mesafeli satış ve cayma hakkı bilgisi.', 1, 5);
